---
version: 2.1

jobs:
  #
  # Tests Lint + E2E w/ molecule
  #
  test-static-code-linting-and-e2e:
    machine:
      image: ubuntu-1604:202007-01
      # This job has been blocked because Docker Layer Caching is not available on your plan.
      # Please upgrade to continue building.
      # Note: you will need to push a new commit or call the API to rerun the pipeline.
      docker_layer_caching: false

    steps:
      - checkout

      - run:
          name: Context Info Cmds
          command: pwd && ls -ltra && git branch

      - run:
          name: Initialize Repo Makefiles
          command: |
            make init-makefiles
            git update-index --assume-unchanged "Makefile"

      - run:
          name: tests-init
          command: make init

      - run:
          name: tests-ansible-molecule-lint-e2e
          command: make test-molecule-local

  #
  # Release
  #
  release-version-with-changelog:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: false

    environment:
      VERSION_NUMBER: patch # opts: patch, minor or major.

    steps:
      - checkout

      - run:
          name: Context Info Cmds
          command: pwd && ls -ltra && git branch

      - run:
          name: Initialize Repo Makefiles
          command: |
            make init-makefiles
            git update-index --assume-unchanged "Makefile"

      - run:
          name: Release New Version
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-$VERSION_NUMBER-with-changelog-circleci"
              echo "==============================================================================================="
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              make release-$VERSION_NUMBER-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi

      - run:
          name: ansible-init
          command: make init

      - run:
          name: ansible-galaxy-import-role
          command: make ANSIBLE_GALAXY_API_KEY=$ANSIBLE_GALAXY_API_KEY ansible-galaxy-import-role

#
# Jobs workflow
#
workflows:
  version: 2
  test_and_release:
    jobs:
      - test-static-code-linting-and-e2e:
          context: binbashar-org-global-context
          filters:
            branches:
              # only branches matching the below regex filters will run
              ignore:
                - master
      - release-version-with-changelog:
          context: binbashar-org-global-context
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master
