---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c ./molecule/default/yaml-lint.yml .
  ansible-lint --exclude ./.chglog/ ./.circleci/ ./.github/ ./@bin/makefiles/ ./molecule/default/roles/
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pull: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
